/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fAFWWEgeBrsii99MoRQ4aq
// Component: yifqr28lPCx-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdModal } from "@plasmicpkgs/antd5/skinny/registerModal";
import ContactDetailComponent from "../../ContactDetailComponent"; // plasmic-import: g4h5919t8tep/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectcss
import sty from "./PlasmicContactListComponent.module.css"; // plasmic-import: yifqr28lPCx-/css

createPlasmicElementProxy;

export type PlasmicContactListComponent__VariantMembers = {};
export type PlasmicContactListComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactListComponent__VariantsArgs;
export const PlasmicContactListComponent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicContactListComponent__ArgsType = { currentItem?: any };
type ArgPropType = keyof PlasmicContactListComponent__ArgsType;
export const PlasmicContactListComponent__ArgProps = new Array<ArgPropType>(
  "currentItem"
);

export type PlasmicContactListComponent__OverridesType = {
  contactListComponente?: Flex__<"section">;
  contactHorizontalStack?: Flex__<"div">;
  imageContactImage?: Flex__<typeof PlasmicImg__>;
  contactVerticalStack?: Flex__<"div">;
  nameContactText?: Flex__<"div">;
  emailContactText?: Flex__<"div">;
  detailContactModal?: Flex__<typeof AntdModal>;
  contactDetailComponent?: Flex__<typeof ContactDetailComponent>;
  titleDetailContactModalText?: Flex__<"div">;
  showDetailContactModalButton?: Flex__<typeof AntdButton>;
  text?: Flex__<"div">;
  closeDetailContactModalButton?: Flex__<typeof AntdButton>;
  closeDetailContactModalButtonText?: Flex__<"div">;
};

export interface DefaultContactListComponentProps {
  currentItem?: any;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContactListComponent__RenderFunc(props: {
  variants: PlasmicContactListComponent__VariantsArgs;
  args: PlasmicContactListComponent__ArgsType;
  overrides: PlasmicContactListComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "detailContactModal.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <section
      data-plasmic-name={"contactListComponente"}
      data-plasmic-override={overrides.contactListComponente}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.contactListComponente
      )}
    >
      <div
        data-plasmic-name={"contactHorizontalStack"}
        data-plasmic-override={overrides.contactHorizontalStack}
        className={classNames(projectcss.all, sty.contactHorizontalStack)}
      >
        <PlasmicImg__
          data-plasmic-name={"imageContactImage"}
          data-plasmic-override={overrides.imageContactImage}
          alt={(() => {
            try {
              return $props.currentItem.name;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          className={classNames(sty.imageContactImage)}
          displayHeight={"100%"}
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"92px"}
          height={``}
          loading={"lazy"}
          src={(() => {
            try {
              return $props.currentItem.image;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          width={``}
        />

        <div
          data-plasmic-name={"contactVerticalStack"}
          data-plasmic-override={overrides.contactVerticalStack}
          className={classNames(projectcss.all, sty.contactVerticalStack)}
        >
          <div
            data-plasmic-name={"nameContactText"}
            data-plasmic-override={overrides.nameContactText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.nameContactText
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.currentItem.name;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "contact name";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <div
            data-plasmic-name={"emailContactText"}
            data-plasmic-override={overrides.emailContactText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.emailContactText
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.currentItem.email;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
        <AntdModal
          data-plasmic-name={"detailContactModal"}
          data-plasmic-override={overrides.detailContactModal}
          className={classNames("__wab_instance", sty.detailContactModal)}
          defaultStylesClassName={classNames(
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames
          )}
          footer={
            <AntdButton
              data-plasmic-name={"closeDetailContactModalButton"}
              data-plasmic-override={overrides.closeDetailContactModalButton}
              className={classNames(
                "__wab_instance",
                sty.closeDetailContactModalButton
              )}
              danger={true}
              disabled={false}
              ghost={false}
              loading={false}
              onClick={async () => {
                const $steps = {};

                $steps["updateDetailContactModalOpen"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["detailContactModal", "open"]
                        },
                        operation: 0,
                        value: false
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateDetailContactModalOpen"] != null &&
                  typeof $steps["updateDetailContactModalOpen"] === "object" &&
                  typeof $steps["updateDetailContactModalOpen"].then ===
                    "function"
                ) {
                  $steps["updateDetailContactModalOpen"] =
                    await $steps["updateDetailContactModalOpen"];
                }
              }}
              size={"large"}
              type={"primary"}
            >
              <div
                data-plasmic-name={"closeDetailContactModalButtonText"}
                data-plasmic-override={
                  overrides.closeDetailContactModalButtonText
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.closeDetailContactModalButtonText
                )}
              >
                {"Fechar"}
              </div>
            </AntdButton>
          }
          modalScopeClassName={sty["detailContactModal__modal"]}
          onOpenChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "detailContactModal",
              "open"
            ]).apply(null, eventArgs);
          }}
          open={generateStateValueProp($state, ["detailContactModal", "open"])}
          title={
            <div
              data-plasmic-name={"titleDetailContactModalText"}
              data-plasmic-override={overrides.titleDetailContactModalText}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.titleDetailContactModalText
              )}
            >
              {"Detalhes"}
            </div>
          }
          trigger={
            <AntdButton
              data-plasmic-name={"showDetailContactModalButton"}
              data-plasmic-override={overrides.showDetailContactModalButton}
              className={classNames(
                "__wab_instance",
                sty.showDetailContactModalButton
              )}
              size={"large"}
              type={"primary"}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"Detalhes"}
              </div>
            </AntdButton>
          }
          width={"600"}
        >
          <ContactDetailComponent
            data-plasmic-name={"contactDetailComponent"}
            data-plasmic-override={overrides.contactDetailComponent}
            className={classNames("__wab_instance", sty.contactDetailComponent)}
            contact={(() => {
              try {
                return $props.currentItem;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        </AntdModal>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  contactListComponente: [
    "contactListComponente",
    "contactHorizontalStack",
    "imageContactImage",
    "contactVerticalStack",
    "nameContactText",
    "emailContactText",
    "detailContactModal",
    "contactDetailComponent",
    "titleDetailContactModalText",
    "showDetailContactModalButton",
    "text",
    "closeDetailContactModalButton",
    "closeDetailContactModalButtonText"
  ],
  contactHorizontalStack: [
    "contactHorizontalStack",
    "imageContactImage",
    "contactVerticalStack",
    "nameContactText",
    "emailContactText",
    "detailContactModal",
    "contactDetailComponent",
    "titleDetailContactModalText",
    "showDetailContactModalButton",
    "text",
    "closeDetailContactModalButton",
    "closeDetailContactModalButtonText"
  ],
  imageContactImage: ["imageContactImage"],
  contactVerticalStack: [
    "contactVerticalStack",
    "nameContactText",
    "emailContactText"
  ],
  nameContactText: ["nameContactText"],
  emailContactText: ["emailContactText"],
  detailContactModal: [
    "detailContactModal",
    "contactDetailComponent",
    "titleDetailContactModalText",
    "showDetailContactModalButton",
    "text",
    "closeDetailContactModalButton",
    "closeDetailContactModalButtonText"
  ],
  contactDetailComponent: ["contactDetailComponent"],
  titleDetailContactModalText: ["titleDetailContactModalText"],
  showDetailContactModalButton: ["showDetailContactModalButton", "text"],
  text: ["text"],
  closeDetailContactModalButton: [
    "closeDetailContactModalButton",
    "closeDetailContactModalButtonText"
  ],
  closeDetailContactModalButtonText: ["closeDetailContactModalButtonText"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  contactListComponente: "section";
  contactHorizontalStack: "div";
  imageContactImage: typeof PlasmicImg__;
  contactVerticalStack: "div";
  nameContactText: "div";
  emailContactText: "div";
  detailContactModal: typeof AntdModal;
  contactDetailComponent: typeof ContactDetailComponent;
  titleDetailContactModalText: "div";
  showDetailContactModalButton: typeof AntdButton;
  text: "div";
  closeDetailContactModalButton: typeof AntdButton;
  closeDetailContactModalButtonText: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactListComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactListComponent__VariantsArgs;
    args?: PlasmicContactListComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContactListComponent__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContactListComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContactListComponent__ArgProps,
          internalVariantPropNames: PlasmicContactListComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContactListComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "contactListComponente") {
    func.displayName = "PlasmicContactListComponent";
  } else {
    func.displayName = `PlasmicContactListComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicContactListComponent = Object.assign(
  // Top-level PlasmicContactListComponent renders the root element
  makeNodeComponent("contactListComponente"),
  {
    // Helper components rendering sub-elements
    contactHorizontalStack: makeNodeComponent("contactHorizontalStack"),
    imageContactImage: makeNodeComponent("imageContactImage"),
    contactVerticalStack: makeNodeComponent("contactVerticalStack"),
    nameContactText: makeNodeComponent("nameContactText"),
    emailContactText: makeNodeComponent("emailContactText"),
    detailContactModal: makeNodeComponent("detailContactModal"),
    contactDetailComponent: makeNodeComponent("contactDetailComponent"),
    titleDetailContactModalText: makeNodeComponent(
      "titleDetailContactModalText"
    ),
    showDetailContactModalButton: makeNodeComponent(
      "showDetailContactModalButton"
    ),
    text: makeNodeComponent("text"),
    closeDetailContactModalButton: makeNodeComponent(
      "closeDetailContactModalButton"
    ),
    closeDetailContactModalButtonText: makeNodeComponent(
      "closeDetailContactModalButtonText"
    ),

    // Metadata about props expected for PlasmicContactListComponent
    internalVariantProps: PlasmicContactListComponent__VariantProps,
    internalArgProps: PlasmicContactListComponent__ArgProps
  }
);

export default PlasmicContactListComponent;
/* prettier-ignore-end */
