/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fAFWWEgeBrsii99MoRQ4aq
// Component: AHyXHfhQvsc6

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown";
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectcss
import sty from "./PlasmicPageTitleComponent.module.css"; // plasmic-import: AHyXHfhQvsc6/css

import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: z8k2lIno0OvB/icon
import UserSearchIcon from "./icons/PlasmicIcon__UserSearch"; // plasmic-import: aiJ_ISlKTfEF/icon

createPlasmicElementProxy;

export type PlasmicPageTitleComponent__VariantMembers = {};
export type PlasmicPageTitleComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicPageTitleComponent__VariantsArgs;
export const PlasmicPageTitleComponent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPageTitleComponent__ArgsType = {
  title?: string;
  actions?: any;
};
type ArgPropType = keyof PlasmicPageTitleComponent__ArgsType;
export const PlasmicPageTitleComponent__ArgProps = new Array<ArgPropType>(
  "title",
  "actions"
);

export type PlasmicPageTitleComponent__OverridesType = {
  pageTitleComponent?: Flex__<"div">;
  leftDropdown?: Flex__<typeof AntdDropdown>;
  freeBox?: Flex__<"div">;
  pageTitleText?: Flex__<"div">;
  chevronDownImage?: Flex__<"svg">;
  centerHorizontalStack?: Flex__<"div">;
  rightHorizontalStack?: Flex__<"div">;
  searchUserButton?: Flex__<typeof AntdButton>;
  searchUserImage?: Flex__<"svg">;
};

export interface DefaultPageTitleComponentProps {
  title?: string;
  actions?: any;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPageTitleComponent__RenderFunc(props: {
  variants: PlasmicPageTitleComponent__VariantsArgs;
  args: PlasmicPageTitleComponent__ArgsType;
  overrides: PlasmicPageTitleComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          actions: []
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"pageTitleComponent"}
      data-plasmic-override={overrides.pageTitleComponent}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.pageTitleComponent
      )}
    >
      <AntdDropdown
        data-plasmic-name={"leftDropdown"}
        data-plasmic-override={overrides.leftDropdown}
        className={classNames("__wab_instance", sty.leftDropdown)}
        dropdownMenuScopeClassName={sty["leftDropdown__dropdownMenu"]}
        menuItems={() => (
          <React.Fragment>
            <AntdMenuItem
              className={classNames("__wab_instance", sty.menuItem__buul8)}
              key={"menu-item-1"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uwHdh
                )}
              >
                {"Menu item"}
              </div>
            </AntdMenuItem>
            <AntdMenuItem
              className={classNames("__wab_instance", sty.menuItem__anOz5)}
              key={"menu-item-2"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bDeMg
                )}
              >
                {"Menu item"}
              </div>
            </AntdMenuItem>
          </React.Fragment>
        )}
        menuItemsJson={(() => {
          try {
            return $props.actions;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return [
                { type: "item", value: "action1", label: "Action 1" },
                { type: "item", value: "action2", label: "Action 2" }
              ];
            }
            throw e;
          }
        })()}
        placement={"bottomRight"}
        trigger={"hover"}
        useMenuItemsSlot={false}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <div
            data-plasmic-name={"pageTitleText"}
            data-plasmic-override={overrides.pageTitleText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.pageTitleText
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.title;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <ChevronDownIcon
            data-plasmic-name={"chevronDownImage"}
            data-plasmic-override={overrides.chevronDownImage}
            className={classNames(projectcss.all, sty.chevronDownImage)}
            role={"img"}
          />
        </div>
      </AntdDropdown>
      <div
        data-plasmic-name={"centerHorizontalStack"}
        data-plasmic-override={overrides.centerHorizontalStack}
        className={classNames(projectcss.all, sty.centerHorizontalStack)}
      />

      <div
        data-plasmic-name={"rightHorizontalStack"}
        data-plasmic-override={overrides.rightHorizontalStack}
        className={classNames(projectcss.all, sty.rightHorizontalStack)}
      >
        <AntdButton
          data-plasmic-name={"searchUserButton"}
          data-plasmic-override={overrides.searchUserButton}
          className={classNames("__wab_instance", sty.searchUserButton)}
          danger={false}
          disabled={false}
          ghost={false}
          loading={false}
          shape={"default"}
          size={"large"}
          submitsForm={false}
          type={"default"}
        >
          <UserSearchIcon
            data-plasmic-name={"searchUserImage"}
            data-plasmic-override={overrides.searchUserImage}
            className={classNames(projectcss.all, sty.searchUserImage)}
            role={"img"}
          />
        </AntdButton>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  pageTitleComponent: [
    "pageTitleComponent",
    "leftDropdown",
    "freeBox",
    "pageTitleText",
    "chevronDownImage",
    "centerHorizontalStack",
    "rightHorizontalStack",
    "searchUserButton",
    "searchUserImage"
  ],
  leftDropdown: [
    "leftDropdown",
    "freeBox",
    "pageTitleText",
    "chevronDownImage"
  ],
  freeBox: ["freeBox", "pageTitleText", "chevronDownImage"],
  pageTitleText: ["pageTitleText"],
  chevronDownImage: ["chevronDownImage"],
  centerHorizontalStack: ["centerHorizontalStack"],
  rightHorizontalStack: [
    "rightHorizontalStack",
    "searchUserButton",
    "searchUserImage"
  ],
  searchUserButton: ["searchUserButton", "searchUserImage"],
  searchUserImage: ["searchUserImage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  pageTitleComponent: "div";
  leftDropdown: typeof AntdDropdown;
  freeBox: "div";
  pageTitleText: "div";
  chevronDownImage: "svg";
  centerHorizontalStack: "div";
  rightHorizontalStack: "div";
  searchUserButton: typeof AntdButton;
  searchUserImage: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPageTitleComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPageTitleComponent__VariantsArgs;
    args?: PlasmicPageTitleComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPageTitleComponent__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPageTitleComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPageTitleComponent__ArgProps,
          internalVariantPropNames: PlasmicPageTitleComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPageTitleComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "pageTitleComponent") {
    func.displayName = "PlasmicPageTitleComponent";
  } else {
    func.displayName = `PlasmicPageTitleComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicPageTitleComponent = Object.assign(
  // Top-level PlasmicPageTitleComponent renders the root element
  makeNodeComponent("pageTitleComponent"),
  {
    // Helper components rendering sub-elements
    leftDropdown: makeNodeComponent("leftDropdown"),
    freeBox: makeNodeComponent("freeBox"),
    pageTitleText: makeNodeComponent("pageTitleText"),
    chevronDownImage: makeNodeComponent("chevronDownImage"),
    centerHorizontalStack: makeNodeComponent("centerHorizontalStack"),
    rightHorizontalStack: makeNodeComponent("rightHorizontalStack"),
    searchUserButton: makeNodeComponent("searchUserButton"),
    searchUserImage: makeNodeComponent("searchUserImage"),

    // Metadata about props expected for PlasmicPageTitleComponent
    internalVariantProps: PlasmicPageTitleComponent__VariantProps,
    internalArgProps: PlasmicPageTitleComponent__ArgProps
  }
);

export default PlasmicPageTitleComponent;
/* prettier-ignore-end */
