/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fAFWWEgeBrsii99MoRQ4aq
// Component: qHtcGiMc-dAA

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import PageTitleComponent from "../../PageTitleComponent"; // plasmic-import: AHyXHfhQvsc6/component
import ContactListComponent from "../../ContactListComponent"; // plasmic-import: yifqr28lPCx-/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: qHtcGiMc-dAA/css

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  contactPage?: Flex__<"div">;
  pageTitleComponent?: Flex__<typeof PageTitleComponent>;
  contactListComponent?: Flex__<typeof ContactListComponent>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "contacts",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            name: "Patrizio Randalson",
            email: "prandalson0@prlog.org",
            image:
              "https://thispersonnotexist.org/downloadimage/Ac3RhdGljL21hbi9zZWVkNDYwMDUuanBlZw=="
          },
          {
            name: "Demetris Korb",
            email: "dkorb0@mit.edu",
            image:
              "https://thispersonnotexist.org/downloadimage/Ac3RhdGljL21hbi9zZWVkMTY0NDkuanBlZw=="
          },
          {
            name: "Riley Wimlet",
            email: "rwimlet2@spiegel.de",
            image:
              "https://thispersonnotexist.org/downloadimage/Ac3RhdGljL21hbi9zZWVkMzA5ODcuanBlZw=="
          },
          {
            name: "Ruperto Catterson",
            email: "rcatterson3@sitemeter.com",
            image:
              "https://thispersonnotexist.org/downloadimage/Ac3RhdGljL21hbi9zZWVkOTYzMC5qcGVn"
          },
          {
            name: "Carolin Rainy",
            email: "crainy4@sakura.ne.jp",
            image:
              "https://thispersonnotexist.org/downloadimage/Ac3RhdGljL21hbi9zZWVkNDc4NjcuanBlZw=="
          },
          {
            name: "Orville Duesbury",
            email: "oduesbury5@mit.edu",
            image:
              "https://thispersonnotexist.org/downloadimage/Ac3RhdGljL3dvbWFuL3NlZWQ0MDYyNi5qcGVn"
          }
        ]
      },
      {
        path: "titulo",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "Contatos"
      },
      {
        path: "contactSelected",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => null
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"contactPage"}
        data-plasmic-override={overrides.contactPage}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.contactPage
        )}
      >
        <PageTitleComponent
          data-plasmic-name={"pageTitleComponent"}
          data-plasmic-override={overrides.pageTitleComponent}
          actions={[
            { label: "\u2795 Novo contato" },
            { type: "divider" },
            { label: "Ordenar A-Z" },
            { label: "Ordenar Z-A" }
          ]}
          className={classNames("__wab_instance", sty.pageTitleComponent)}
          title={"Contatos"}
        />

        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
          (() => {
            try {
              return $state.contacts;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
        ).map((__plasmic_item_0, __plasmic_idx_0) => {
          const currentItem = __plasmic_item_0;
          const currentIndex = __plasmic_idx_0;
          return (
            <ContactListComponent
              data-plasmic-name={"contactListComponent"}
              data-plasmic-override={overrides.contactListComponent}
              className={classNames("__wab_instance", sty.contactListComponent)}
              currentItem={currentItem}
              key={currentIndex}
            />
          );
        })}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  contactPage: ["contactPage", "pageTitleComponent", "contactListComponent"],
  pageTitleComponent: ["pageTitleComponent"],
  contactListComponent: ["contactListComponent"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  contactPage: "div";
  pageTitleComponent: typeof PageTitleComponent;
  contactListComponent: typeof ContactListComponent;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "contactPage") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("contactPage"),
  {
    // Helper components rendering sub-elements
    pageTitleComponent: makeNodeComponent("pageTitleComponent"),
    contactListComponent: makeNodeComponent("contactListComponent"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Contatos",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
