/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fAFWWEgeBrsii99MoRQ4aq
// Component: g4h5919t8tep

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fAFWWEgeBrsii99MoRQ4aq/projectcss
import sty from "./PlasmicContactDetailComponent.module.css"; // plasmic-import: g4h5919t8tep/css

createPlasmicElementProxy;

export type PlasmicContactDetailComponent__VariantMembers = {};
export type PlasmicContactDetailComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactDetailComponent__VariantsArgs;
export const PlasmicContactDetailComponent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicContactDetailComponent__ArgsType = { contact?: any };
type ArgPropType = keyof PlasmicContactDetailComponent__ArgsType;
export const PlasmicContactDetailComponent__ArgProps = new Array<ArgPropType>(
  "contact"
);

export type PlasmicContactDetailComponent__OverridesType = {
  contactDetailVerticalStack?: Flex__<"div">;
  contactDetail01HorizontalStack?: Flex__<"div">;
  contactDetail0101Image?: Flex__<typeof PlasmicImg__>;
  contactDetail0102VerticalStack?: Flex__<"div">;
  nameContactDetailText?: Flex__<"div">;
  emailContactDetailText?: Flex__<"div">;
};

export interface DefaultContactDetailComponentProps {
  contact?: any;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContactDetailComponent__RenderFunc(props: {
  variants: PlasmicContactDetailComponent__VariantsArgs;
  args: PlasmicContactDetailComponent__ArgsType;
  overrides: PlasmicContactDetailComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"contactDetailVerticalStack"}
      data-plasmic-override={overrides.contactDetailVerticalStack}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.contactDetailVerticalStack
      )}
    >
      <div
        data-plasmic-name={"contactDetail01HorizontalStack"}
        data-plasmic-override={overrides.contactDetail01HorizontalStack}
        className={classNames(
          projectcss.all,
          sty.contactDetail01HorizontalStack
        )}
      >
        <PlasmicImg__
          data-plasmic-name={"contactDetail0101Image"}
          data-plasmic-override={overrides.contactDetail0101Image}
          alt={""}
          className={classNames(sty.contactDetail0101Image)}
          displayHeight={"100%"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"auto"}
          height={``}
          loading={"eager"}
          src={(() => {
            try {
              return $props.contact?.image;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          width={"170px"}
        />

        <div
          data-plasmic-name={"contactDetail0102VerticalStack"}
          data-plasmic-override={overrides.contactDetail0102VerticalStack}
          className={classNames(
            projectcss.all,
            sty.contactDetail0102VerticalStack
          )}
        >
          <div
            data-plasmic-name={"nameContactDetailText"}
            data-plasmic-override={overrides.nameContactDetailText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.nameContactDetailText
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.contact?.name;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "contact name";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <div
            data-plasmic-name={"emailContactDetailText"}
            data-plasmic-override={overrides.emailContactDetailText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.emailContactDetailText
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.contact?.email;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "contact email";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  contactDetailVerticalStack: [
    "contactDetailVerticalStack",
    "contactDetail01HorizontalStack",
    "contactDetail0101Image",
    "contactDetail0102VerticalStack",
    "nameContactDetailText",
    "emailContactDetailText"
  ],
  contactDetail01HorizontalStack: [
    "contactDetail01HorizontalStack",
    "contactDetail0101Image",
    "contactDetail0102VerticalStack",
    "nameContactDetailText",
    "emailContactDetailText"
  ],
  contactDetail0101Image: ["contactDetail0101Image"],
  contactDetail0102VerticalStack: [
    "contactDetail0102VerticalStack",
    "nameContactDetailText",
    "emailContactDetailText"
  ],
  nameContactDetailText: ["nameContactDetailText"],
  emailContactDetailText: ["emailContactDetailText"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  contactDetailVerticalStack: "div";
  contactDetail01HorizontalStack: "div";
  contactDetail0101Image: typeof PlasmicImg__;
  contactDetail0102VerticalStack: "div";
  nameContactDetailText: "div";
  emailContactDetailText: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactDetailComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactDetailComponent__VariantsArgs;
    args?: PlasmicContactDetailComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContactDetailComponent__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContactDetailComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContactDetailComponent__ArgProps,
          internalVariantPropNames: PlasmicContactDetailComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContactDetailComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "contactDetailVerticalStack") {
    func.displayName = "PlasmicContactDetailComponent";
  } else {
    func.displayName = `PlasmicContactDetailComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicContactDetailComponent = Object.assign(
  // Top-level PlasmicContactDetailComponent renders the root element
  makeNodeComponent("contactDetailVerticalStack"),
  {
    // Helper components rendering sub-elements
    contactDetail01HorizontalStack: makeNodeComponent(
      "contactDetail01HorizontalStack"
    ),
    contactDetail0101Image: makeNodeComponent("contactDetail0101Image"),
    contactDetail0102VerticalStack: makeNodeComponent(
      "contactDetail0102VerticalStack"
    ),
    nameContactDetailText: makeNodeComponent("nameContactDetailText"),
    emailContactDetailText: makeNodeComponent("emailContactDetailText"),

    // Metadata about props expected for PlasmicContactDetailComponent
    internalVariantProps: PlasmicContactDetailComponent__VariantProps,
    internalArgProps: PlasmicContactDetailComponent__ArgProps
  }
);

export default PlasmicContactDetailComponent;
/* prettier-ignore-end */
